works on plaidml
fix 
PROD AggregationOp does not support derivatives yet
and
alueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()